# Form implementation generated from reading ui file 'text_editor.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 686)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("font-size: 10pt;")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(42, 42, 42);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=self.frame)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.inputTabWidget = QtWidgets.QTabWidget(parent=self.splitter)
        self.inputTabWidget.setAutoFillBackground(False)
        self.inputTabWidget.setDocumentMode(False)
        self.inputTabWidget.setTabsClosable(True)
        self.inputTabWidget.setMovable(True)
        self.inputTabWidget.setObjectName("inputTabWidget")
        self.outputTabWidget = QtWidgets.QTabWidget(parent=self.splitter)
        self.outputTabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.outputTabWidget.setAutoFillBackground(False)
        self.outputTabWidget.setDocumentMode(False)
        self.outputTabWidget.setTabsClosable(True)
        self.outputTabWidget.setMovable(True)
        self.outputTabWidget.setTabBarAutoHide(False)
        self.outputTabWidget.setObjectName("outputTabWidget")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolBar.setMouseTracking(False)
        self.toolBar.setStyleSheet("QToolBar {\n"
"    background-color: rgb(32, 32, 32);\n"
"    border: none;\n"
"    padding: 2px;\n"
"    spacing: 3px;\n"
"}\n"
"\n"
"QToolBar::handle {\n"
"    background-color: rgb(60, 60, 60);\n"
"    width: 4px;\n"
"    border-radius: 2px;\n"
"    margin: 4px 2px;\n"
"}\n"
"\n"
"QToolBar::handle:vertical {\n"
"    height: 4px;\n"
"    width: 20px;\n"
"    margin: 2px 4px;\n"
"}\n"
"\n"
"QToolBar::separator:vertical {\n"
"    width: 20px;\n"
"    height: 2px;\n"
"    margin: 4px 2px;\n"
"}\n"
"\n"
"QToolBar::separator {\n"
"    background-color: rgb(60, 60, 60);\n"
"    width: 2px;\n"
"    height: 20px;\n"
"    margin: 4px 2px;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    color: rgb(224, 224, 224);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"    min-width: 24px;\n"
"    min-height: 24px;\n"
"    margin: 1px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(13, 102, 175);\n"
"    border-bottom: 2px solid rgb(0, 0, 0);\n"
"    border-right: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(16, 125, 220);\n"
"    border-bottom: 2px solid rgb(0, 0, 0);\n"
"    border-right: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    color: rgb(85, 85, 85);\n"
"}\n"
"\n"
"QToolButton QIcon {\n"
"    color: rgb(224, 224, 224);\n"
"}")
        self.toolBar.setMovable(True)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 851, 44))
        self.menuBar.setStyleSheet("QMenuBar {\n"
"    background-color: rgb(32, 32, 32);\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 8px 12px;\n"
"    margin: 3px 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: rgb(13, 102, 175);\n"
"    border-bottom: 2px solid rgb(0, 0, 0);\n"
"    border-right: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background-color: rgb(16, 125, 220);\n"
"    border-bottom: 2px solid rgb(0, 0, 0);\n"
"    border-right: 2px solid rgb(0, 0, 0);\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: rgb(37, 37, 37);\n"
"    color: rgb(224, 224, 224);\n"
"    border: 1px solid rgb(60,  60,  60);\n"
"    border-radius: 5px;\n"
"    padding: 4px 0;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: transparent;\n"
"    padding: 6px 24px 6px 5px;\n"
"    margin: 2px 4px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: rgb(60, 60, 60);\n"
"    margin: 4px 8px;\n"
"}")
        self.menuBar.setDefaultUp(False)
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(parent=self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuText = QtWidgets.QMenu(parent=self.menuBar)
        self.menuText.setObjectName("menuText")
        self.menuRun = QtWidgets.QMenu(parent=self.menuBar)
        self.menuRun.setObjectName("menuRun")
        self.menuSettings = QtWidgets.QMenu(parent=self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionUndo = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.EditUndo)
        self.actionUndo.setIcon(icon)
        self.actionUndo.setObjectName("actionUndo")
        self.actionCut = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.EditCut)
        self.actionCut.setIcon(icon)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.EditCopy)
        self.actionCopy.setIcon(icon)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.EditPaste)
        self.actionPaste.setIcon(icon)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.EditDelete)
        self.actionDelete.setIcon(icon)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelectAll = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.EditSelectAll)
        self.actionSelectAll.setIcon(icon)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.action_15 = QtGui.QAction(parent=MainWindow)
        self.action_15.setObjectName("action_15")
        self.action_16 = QtGui.QAction(parent=MainWindow)
        self.action_16.setObjectName("action_16")
        self.action_17 = QtGui.QAction(parent=MainWindow)
        self.action_17.setObjectName("action_17")
        self.action_18 = QtGui.QAction(parent=MainWindow)
        self.action_18.setObjectName("action_18")
        self.action_19 = QtGui.QAction(parent=MainWindow)
        self.action_19.setObjectName("action_19")
        self.action_20 = QtGui.QAction(parent=MainWindow)
        self.action_20.setObjectName("action_20")
        self.action_21 = QtGui.QAction(parent=MainWindow)
        self.action_21.setObjectName("action_21")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.HelpAbout)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.HelpFaq)
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.DocumentSave)
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.FolderOpen)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.DocumentNew)
        self.actionNew.setIcon(icon)
        self.actionNew.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionNew.setObjectName("actionNew")
        self.actionSaveAs = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.DocumentSaveAs)
        self.actionSaveAs.setIcon(icon)
        self.actionSaveAs.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.ApplicationExit)
        self.actionExit.setIcon(icon)
        self.actionExit.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionExit.setObjectName("actionExit")
        self.actionRedo = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.EditRedo)
        self.actionRedo.setIcon(icon)
        self.actionRedo.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionRedo.setObjectName("actionRedo")
        self.actionRun = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.MediaPlaybackStart)
        self.actionRun.setIcon(icon)
        self.actionRun.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionRun.setObjectName("actionRun")
        self.actionLanguage = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.ToolsCheckSpelling)
        self.actionLanguage.setIcon(icon)
        self.actionLanguage.setObjectName("actionLanguage")
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelectAll)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuText.addAction(self.action_15)
        self.menuText.addAction(self.action_16)
        self.menuText.addAction(self.action_17)
        self.menuText.addAction(self.action_18)
        self.menuText.addAction(self.action_19)
        self.menuText.addAction(self.action_20)
        self.menuText.addAction(self.action_21)
        self.menuSettings.addAction(self.actionLanguage)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuText.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.inputTabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Editor"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuEdit.setTitle(_translate("MainWindow", "Правка"))
        self.menuHelp.setTitle(_translate("MainWindow", "Справка"))
        self.menuText.setTitle(_translate("MainWindow", "Текст"))
        self.menuRun.setTitle(_translate("MainWindow", "Пуск"))
        self.menuSettings.setTitle(_translate("MainWindow", "Настройки"))
        self.actionUndo.setText(_translate("MainWindow", "Отменить"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionCut.setText(_translate("MainWindow", "Вырезать"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Копировать"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Вставить"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionDelete.setText(_translate("MainWindow", "Удалить"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Del"))
        self.actionSelectAll.setText(_translate("MainWindow", "Выделить всё"))
        self.actionSelectAll.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.action_15.setText(_translate("MainWindow", "Постановка задачи"))
        self.action_16.setText(_translate("MainWindow", "Грамматика"))
        self.action_17.setText(_translate("MainWindow", "Классификация грамматики"))
        self.action_18.setText(_translate("MainWindow", "Метод анализа"))
        self.action_19.setText(_translate("MainWindow", "Тестовый пример"))
        self.action_20.setText(_translate("MainWindow", "Список литературы"))
        self.action_21.setText(_translate("MainWindow", "Исходный код программы"))
        self.actionAbout.setText(_translate("MainWindow", "О программе"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F2"))
        self.actionHelp.setText(_translate("MainWindow", "Вызов справки"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
        self.actionSave.setText(_translate("MainWindow", "Сохранить"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Открыть"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNew.setText(_translate("MainWindow", "Создать"))
        self.actionNew.setToolTip(_translate("MainWindow", "Создать"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSaveAs.setText(_translate("MainWindow", "Сохранить как"))
        self.actionSaveAs.setToolTip(_translate("MainWindow", "Сохранить как"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionExit.setToolTip(_translate("MainWindow", "Выход"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionRedo.setText(_translate("MainWindow", "Повторить"))
        self.actionRedo.setToolTip(_translate("MainWindow", "Повторить"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionRun.setText(_translate("MainWindow", "Пуск"))
        self.actionRun.setToolTip(_translate("MainWindow", "Пуск"))
        self.actionRun.setShortcut(_translate("MainWindow", "F5"))
        self.actionLanguage.setText(_translate("MainWindow", "Язык"))
